#pragma once
void			CreateGameFont(HFONT* _Font, wchar_t* font_name, int font_size);
WNDCLASSEXW		CreateWindowClass(void);
BOOL			CreateGameWindow(void);
BOOL			GameIsAlreadyRunning(void);
BOOL			InitializeBackBuffer(GAMEBITMAP* bitmap);
BOOL			SetWindowToFullscreen(HWND WindowHandle);
void			ProcessPlayerInput(void);
void			DrawDebugInfo(HDC DeviceContext);
void			RenderFrameGraphics(void);
BOOL			InitializePlayer(PLAYER* player);
void			DrawSprite(int x, int y, int width, int height);
void			DrawSprite2(int x, int y, int width, int height);
void			ClearScreen(void);
void			ClearColor(int red, int green, int blue);
BOOL			InitializeGameMap(void);
BOOL			InitializeGame(void);
BOOL			SetGameToHighPriority(HANDLE ProcessHandle, HANDLE ThreadHandle);
BOOL			Load32BitmapFromFile(_In_ const char* Filename, _Inout_ GAMEBITMAP* Bitmap);
LRESULT			CALLBACK MainWindowProc(_In_ HWND WindowHandle, _In_ unsigned int WindowMessage, _In_ WPARAM WindowParameterWide, _In_ LPARAM WindowParameter);