#pragma once
#include <unordered_map>
std::unordered_map<int, const wchar_t*> SystemErrors = {
    { 1300, L"[Error 1300]: Not all privileges or groups referenced are assigned to the caller." },
    { 1301, L"[Error 1301]: Some mapping between account names and security IDs was not done." },
    { 1302, L"[Error 1302]: No system quota limits are specifically set for this account." },
    { 1303, L"[Error 1303]: No encryption key is available. A well-known encryption key was returned." },
    { 1304, L"[Error 1304]: The password is too complex to be converted to a LAN Manager password. The LAN Manager password returned is a NULL string." },
    { 1305, L"[Error 1305]: The revision level is unknown." },
    { 1306, L"[Error 1306]: Indicates two revision levels are incompatible." },
    { 1307, L"[Error 1307]: This security ID may not be assigned as the owner of this object." },
    { 1308, L"[Error 1308]: This security ID may not be assigned as the primary group of an object." },
    { 1309, L"[Error 1309]: An attempt has been made to operate on an impersonation token by a thread that is not currently impersonating a client." },
    { 1310, L"[Error 1310]: The group may not be disabled." },
    { 1311, L"[Error 1311]: There are currently no logon servers available to service the logon request." },
    { 1312, L"[Error 1312]: A specified logon session does not exist. It may already have been terminated." },
    { 1313, L"[Error 1313]: A specified privilege does not exist." },
    { 1314, L"[Error 1314]: A required privilege is not held by the client." },
    { 1315, L"[Error 1315]: The name provided is not a properly formed account name." },
    { 1316, L"[Error 1316]: The specified account already exists." },
    { 1317, L"[Error 1317]: The specified account does not exist." },
    { 1318, L"[Error 1318]: The specified group already exists." },
    { 1319, L"[Error 1319]: The specified group does not exist." },
    { 1320, L"[Error 1320]: Either the specified user account is already a member of the specified group, or the specified group cannot be deleted because it contains a member." },
    { 1321, L"[Error 1321]: The specified user account is not a member of the specified group account." },
    { 1322, L"[Error 1322]: This operation is disallowed as it could result in an administration account being disabled, deleted or unable to log on." },
    { 1323, L"[Error 1323]: Unable to update the password. The value provided as the current password is incorrect." },
    { 1324, L"[Error 1324]: Unable to update the password. The value provided for the new password contains values that are not allowed in passwords." },
    { 1325, L"[Error 1325]: Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain." },
    { 1326, L"[Error 1326]: The user name or password is incorrect." },
    { 1327, L"[Error 1327]: Account restrictions are preventing this user from signing in. For example: blank passwords aren't allowed, sign-in times are limited, or a policy restriction has been enforced." },
    { 1328, L"[Error 1328]: Your account has time restrictions that keep you from signing in right now." },
    { 1329, L"[Error 1329]: This user isn't allowed to sign in to this computer." },
    { 1330, L"[Error 1330]: The password for this account has expired." },
    { 1331, L"[Error 1331]: This user can't sign in because this account is currently disabled." },
    { 1332, L"[Error 1332]: No mapping between account names and security IDs was done." },
    { 1333, L"[Error 1333]: Too many local user identifiers (LUIDs) were requested at one time." },
    { 1334, L"[Error 1334]: No more local user identifiers (LUIDs) are available." },
    { 1335, L"[Error 1335]: The subauthority part of a security ID is invalid for this particular use." },
    { 1336, L"[Error 1336]: The access control list (ACL) structure is invalid." },
    { 1337, L"[Error 1337]: The security ID structure is invalid." },
    { 1338, L"[Error 1338]: The security descriptor structure is invalid." },
    { 1340, L"[Error 1340]: The inherited access control list (ACL) or access control entry (ACE) could not be built." },
    { 1341, L"[Error 1341]: The server is currently disabled." },
    { 1342, L"[Error 1342]: The server is currently enabled." },
    { 1343, L"[Error 1343]: The value provided was an invalid value for an identifier authority." },
    { 1344, L"[Error 1344]: No more memory is available for security information updates." },
    { 1345, L"[Error 1345]: The specified attributes are invalid, or incompatible with the attributes for the group as a whole." },
    { 1346, L"[Error 1346]: Either a required impersonation level was not provided, or the provided impersonation level is invalid." },
    { 1347, L"[Error 1347]: Cannot open an anonymous level security token." },
    { 1348, L"[Error 1348]: The validation information class requested was invalid." },
    { 1349, L"[Error 1349]: The type of the token is inappropriate for its attempted use." },
    { 1350, L"[Error 1350]: Unable to perform a security operation on an object that has no associated security." },
    { 1351, L"[Error 1351]: Configuration information could not be read from the domain controller, either because the machine is unavailable, or access has been denied." },
    { 1352, L"[Error 1352]: The security account manager (SAM) or local security authority (LSA) server was in the wrong state to perform the security operation." },
    { 1353, L"[Error 1353]: The domain was in the wrong state to perform the security operation." },
    { 1354, L"[Error 1354]: This operation is only allowed for the Primary Domain Controller of the domain." },
    { 1355, L"[Error 1355]: The specified domain either does not exist or could not be contacted." },
    { 1356, L"[Error 1356]: The specified domain already exists." },
    { 1357, L"[Error 1357]: An attempt was made to exceed the limit on the number of domains per server." },
    { 1358, L"[Error 1358]: Unable to complete the requested operation because of either a catastrophic media failure or a data structure corruption on the disk." },
    { 1359, L"[Error 1359]: An internal error occurred." },
    { 1360, L"[Error 1360]: Generic access types were contained in an access mask which should already be mapped to nongeneric types." },
    { 1361, L"[Error 1361]: A security descriptor is not in the right format (absolute or self-relative)." },
    { 1362, L"[Error 1362]: The requested action is restricted for use by logon processes only. The calling process has not registered as a logon process." },
    { 1363, L"[Error 1363]: Cannot start a new logon session with an ID that is already in use." },
    { 1364, L"[Error 1364]: A specified authentication package is unknown." },
    { 1365, L"[Error 1365]: The logon session is not in a state that is consistent with the requested operation." },
    { 1366, L"[Error 1366]: The logon session ID is already in use." },
    { 1367, L"[Error 1367]: A logon request contained an invalid logon type value." },
    { 1368, L"[Error 1368]: Unable to impersonate using a named pipe until data has been read from that pipe." },
    { 1369, L"[Error 1369]: The transaction state of a registry subtree is incompatible with the requested operation." },
    { 1370, L"[Error 1370]: An internal security database corruption has been encountered." },
    { 1371, L"[Error 1371]: Cannot perform this operation on built-in accounts." },
    { 1372, L"[Error 1372]: Cannot perform this operation on this built-in special group." },
    { 1373, L"[Error 1373]: Cannot perform this operation on this built-in special user." },
    { 1374, L"[Error 1374]: The user cannot be removed from a group because the group is currently the user's primary group." },
    { 1375, L"[Error 1375]: The token is already in use as a primary token." },
    { 1376, L"[Error 1376]: The specified local group does not exist." },
    { 1377, L"[Error 1377]: The specified account name is not a member of the group." },
    { 1378, L"[Error 1378]: The specified account name is already a member of the group." },
    { 1379, L"[Error 1379]: The specified local group already exists." },
    { 1380, L"[Error 1380]: Logon failure: the user has not been granted the requested logon type at this computer." },
    { 1381, L"[Error 1381]: The maximum number of secrets that may be stored in a single system has been exceeded." },
    { 1382, L"[Error 1382]: The length of a secret exceeds the maximum length allowed." },
    { 1383, L"[Error 1383]: The local security authority database contains an internal inconsistency." },
    { 1384, L"[Error 1384]: During a logon attempt, the user's security context accumulated too many security IDs." },
    { 1385, L"[Error 1385]: Logon failure: the user has not been granted the requested logon type at this computer." },
    { 1386, L"[Error 1386]: A cross-encrypted password is necessary to change a user password." },
    { 1387, L"[Error 1387]: A member could not be added to or removed from the local group because the member does not exist." },
    { 1388, L"[Error 1388]: A new member could not be added to a local group because the member has the wrong account type." },
    { 1389, L"[Error 1389]: Too many security IDs have been specified." },
    { 1390, L"[Error 1390]: A cross-encrypted password is necessary to change this user password." },
    { 1391, L"[Error 1391]: Indicates an ACL contains no inheritable components." },
    { 1392, L"[Error 1392]: The file or directory is corrupted and unreadable." },
    { 1393, L"[Error 1393]: The disk structure is corrupted and unreadable." },
    { 1394, L"[Error 1394]: There is no user session key for the specified logon session." },
    { 1395, L"[Error 1395]: The service being accessed is licensed for a particular number of connections. No more connections can be made to the service at this time because there are already as many connections as the service can accept." },
    { 1396, L"[Error 1396]: The target account name is incorrect." },
    { 1397, L"[Error 1397]: Mutual Authentication failed. The server's password is out of date at the domain controller." },
    { 1398, L"[Error 1398]: There is a time and/or date difference between the client and server." },
    { 1399, L"[Error 1399]: This operation cannot be performed on the current domain." },
    { 1400, L"[Error 1400]: Invalid window handle." },
    { 1401, L"[Error 1401]: Invalid menu handle." },
    { 1402, L"[Error 1402]: Invalid cursor handle." },
    { 1403, L"[Error 1403]: Invalid accelerator table handle." },
    { 1404, L"[Error 1404]: Invalid hook handle." },
    { 1405, L"[Error 1405]: Invalid handle to a multiple-window position structure." },
    { 1406, L"[Error 1406]: Cannot create a top-level child window." },
    { 1407, L"[Error 1407]: Cannot find window class." },
    { 1408, L"[Error 1408]: Invalid window; it belongs to other thread." },
    { 1409, L"[Error 1409]: Hot key is already registered." },
    { 1410, L"[Error 1410]: Class already exists." },
    { 1411, L"[Error 1411]: Class does not exist." },
    { 1412, L"[Error 1412]: Class still has open windows." },
    { 1413, L"[Error 1413]: Invalid index." },
    { 1414, L"[Error 1414]: Invalid icon handle." },
    { 1415, L"[Error 1415]: Using private DIALOG window words." },
    { 1416, L"[Error 1416]: The list box identifier was not found." },
    { 1417, L"[Error 1417]: No wildcards were found." },
    { 1418, L"[Error 1418]: Thread does not have a clipboard open." },
    { 1419, L"[Error 1419]: Hot key is not registered." },
    { 1420, L"[Error 1420]: The window is not a valid dialog window." },
    { 1421, L"[Error 1421]: Control ID not found." },
    { 1422, L"[Error 1422]: Invalid message for a combo box because it does not have an edit control." },
    { 1423, L"[Error 1423]: The window is not a combo box." },
    { 1424, L"[Error 1424]: Height must be less than 256." },
    { 1425, L"[Error 1425]: Invalid device context (DC) handle." },
    { 1426, L"[Error 1426]: Invalid hook procedure type." },
    { 1427, L"[Error 1427]: Invalid hook procedure." },
    { 1428, L"[Error 1428]: Cannot set nonlocal hook without a module handle." },
    { 1429, L"[Error 1429]: This hook procedure can only be set globally." },
    { 1430, L"[Error 1430]: The journal hook procedure is already installed." },
    { 1431, L"[Error 1431]: The hook procedure is not installed." },
    { 1432, L"[Error 1432]: Invalid message for single-selection list box." },
    { 1433, L"[Error 1433]: LB_SETCOUNT sent to non-lazy list box." },
    { 1434, L"[Error 1434]: This list box does not support tab stops." },
    { 1435, L"[Error 1435]: Cannot destroy object created by another thread." },
    { 1436, L"[Error 1436]: Child windows cannot have menus." },
    { 1437, L"[Error 1437]: The window does not have a system menu." },
    { 1438, L"[Error 1438]: Invalid message box style." },
    { 1439, L"[Error 1439]: Invalid system-wide (SPI_*) parameter." },
    { 1440, L"[Error 1440]: Screen already locked." },
    { 1441, L"[Error 1441]: All handles to windows in a multiple-window position structure must have the same parent." },
    { 1442, L"[Error 1442]: The window is not a child window." },
    { 1443, L"[Error 1443]: Invalid GW_* command." },
    { 1444, L"[Error 1444]: Invalid thread identifier." },
    { 1445, L"[Error 1445]: Cannot process a message from a window that is not a multiple document interface (MDI) window." },
    { 1446, L"[Error 1446]: Popup menu already active." },
    { 1447, L"[Error 1447]: The window does not have scroll bars." },
    { 1448, L"[Error 1448]: Scroll bar range cannot be greater than MAXLONG." },
    { 1449, L"[Error 1449]: Cannot show or remove the window in the way specified." },
    { 1450, L"[Error 1450]: Insufficient system resources exist to complete the requested service." },
    { 1451, L"[Error 1451]: Insufficient system resources exist to complete the requested service." },
    { 1452, L"[Error 1452]: Insufficient system resources exist to complete the requested service." },
    { 1453, L"[Error 1453]: Insufficient quota to complete the requested service." },
    { 1454, L"[Error 1454]: Insufficient quota to complete the requested service." },
    { 1455, L"[Error 1455]: The paging file is too small for this operation to complete." },
    { 1456, L"[Error 1456]: A menu item was not found." },
    { 1457, L"[Error 1457]: Invalid keyboard layout handle." },
    { 1458, L"[Error 1458]: Hook type not allowed." },
    { 1459, L"[Error 1459]: This operation requires an interactive window station." },
    { 1460, L"[Error 1460]: This operation returned because the timeout period expired." },
    { 1461, L"[Error 1461]: Invalid monitor handle." },
    { 1462, L"[Error 1462]: Incorrect size argument." },
    { 1463, L"[Error 1463]: The symbolic link cannot be followed because its type is disabled." },
    { 1464, L"[Error 1464]: This application does not support the current operation on symbolic links." },
    { 1465, L"[Error 1465]: Windows was unable to parse the requested XML data." },
    { 1466, L"[Error 1466]: An error was encountered while processing an XML digital signature." },
    { 1467, L"[Error 1467]: This application must be restarted." },
    { 1468, L"[Error 1468]: The caller made the connection request in the wrong routing compartment." },
    { 1469, L"[Error 1469]: There was an AuthIP failure when attempting to connect to the remote host." },
    { 1470, L"[Error 1470]: Insufficient NVRAM resources exist to complete the requested service. A reboot might be required." },
    { 1471, L"[Error 1471]: Unable to finish the requested operation because the specified process is not a GUI process." },
    { 1500, L"[Error 1500]: The event log file is corrupted." },
    { 1501, L"[Error 1501]: No event log file could be opened, so the event logging service did not start." },
    { 1502, L"[Error 1502]: The event log file is full." },
    { 1503, L"[Error 1503]: The event log file has changed between read operations." },
    { 1550, L"[Error 1550]: The specified task name is invalid." },
    { 1551, L"[Error 1551]: The specified task index is invalid." },
    { 1552, L"[Error 1552]: The specified thread is already joining a task." },
    { 1601, L"[Error 1601]: The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance." },
    { 1602, L"[Error 1602]: User cancelled installation." },
    { 1603, L"[Error 1603]: Fatal error during installation." },
    { 1604, L"[Error 1604]: Installation suspended, incomplete." },
    { 1605, L"[Error 1605]: This action is only valid for products that are currently installed." },
    { 1606, L"[Error 1606]: Feature ID not registered." },
    { 1607, L"[Error 1607]: Component ID not registered." },
    { 1608, L"[Error 1608]: Unknown property." },
    { 1609, L"[Error 1609]: Handle is in an invalid state." },
    { 1610, L"[Error 1610]: The configuration data for this product is corrupt. Contact your support personnel." },
    { 1611, L"[Error 1611]: Component qualifier not present." },
    { 1612, L"[Error 1612]: The installation source for this product is not available. Verify that the source exists and that you can access it." },
    { 1613, L"[Error 1613]: This installation package cannot be installed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service." },
    { 1614, L"[Error 1614]: Product is uninstalled." },
    { 1615, L"[Error 1615]: SQL query syntax invalid or unsupported." },
    { 1616, L"[Error 1616]: Record field does not exist." },
    { 1617, L"[Error 1617]: The device has been removed." },
    { 1618, L"[Error 1618]: Another installation is already in progress. Complete that installation before proceeding with this install." },
    { 1619, L"[Error 1619]: This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package." },
    { 1620, L"[Error 1620]: This installation package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer package." },
    { 1621, L"[Error 1621]: There was an error starting the Windows Installer service user interface. Contact your support personnel." },
    { 1622, L"[Error 1622]: Error opening installation log file. Verify that the specified log file location exists and that you can write to it." },
    { 1623, L"[Error 1623]: The language of this installation package is not supported by your system." },
    { 1624, L"[Error 1624]: Error applying transforms. Verify that the specified transform paths are valid." },
    { 1625, L"[Error 1625]: This installation is forbidden by system policy. Contact your system administrator." },
    { 1626, L"[Error 1626]: Function could not be executed." },
    { 1627, L"[Error 1627]: Function failed during execution." },
    { 1628, L"[Error 1628]: Invalid or unknown table specified." },
    { 1629, L"[Error 1629]: Data supplied is of wrong type." },
    { 1630, L"[Error 1630]: Data of this type is not supported." },
    { 1631, L"[Error 1631]: The Windows Installer service failed to start. Contact your support personnel." },
    { 1632, L"[Error 1632]: The Temp folder is on a drive that is full or is inaccessible. Free up space on the drive or verify that you have write permission on the Temp folder." },
    { 1633, L"[Error 1633]: This installation package is not supported by this processor type. Contact your product vendor." },
    { 1634, L"[Error 1634]: Component not used on this computer." },
    { 1635, L"[Error 1635]: This update package could not be opened. Verify that the update package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer update package." },
    { 1636, L"[Error 1636]: This update package could not be opened. Contact the application vendor to verify that this is a valid Windows Installer update package." },
    { 1637, L"[Error 1637]: This update package cannot be processed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service." },
    { 1638, L"[Error 1638]: Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel." },
    { 1639, L"[Error 1639]: Invalid command line argument. Consult the Windows Installer SDK for detailed command line help." },
    { 1640, L"[Error 1640]: Only administrators have permission to add, remove, or configure server software during a Terminal services remote session. If you want to install or configure software on the server, contact your network administrator." },
    { 1641, L"[Error 1641]: The requested operation completed successfully. The system will be restarted so the changes can take effect." },
    { 1642, L"[Error 1642]: The upgrade cannot be installed by the Windows Installer service because the program to be upgraded may be missing, or the upgrade may update a different version of the program. Verify that the program to be upgraded exists on your computer and that you have the correct upgrade." },
    { 1643, L"[Error 1643]: The update package is not permitted by software restriction policy." },
    { 1644, L"[Error 1644]: One or more customizations are not permitted by software restriction policy." },
    { 1645, L"[Error 1645]: The Windows Installer does not permit installation from a Remote Desktop Connection." },
    { 1646, L"[Error 1646]: Uninstallation of the update package is not supported." },
    { 1647, L"[Error 1647]: The update is not applied to this product." },
    { 1648, L"[Error 1648]: No valid sequence could be found for the set of updates." },
    { 1649, L"[Error 1649]: Update removal was disallowed by policy." },
    { 1650, L"[Error 1650]: The XML update data is invalid." },
    { 1651, L"[Error 1651]: Windows Installer does not permit updating of managed advertised products. At least one feature of the product must be installed before applying the update." },
    { 1652, L"[Error 1652]: The Windows Installer service is not accessible in Safe Mode. Please try again when your computer is not in Safe Mode or you can use System Restore to return your machine to a previous good state." },
    { 1653, L"[Error 1653]: A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately." },
    { 1654, L"[Error 1654]: The app that you are trying to run is not supported on this version of Windows." }
};
